services:
  db:
    image: postgres:15-alpine
    container_name: tifaouine_postgres
    restart: always
    environment:
      POSTGRES_USER: tifaouine_admin
      POSTGRES_PASSWORD: tifaouine_pass
      POSTGRES_DB: tifaouine_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
